// https://en.wikipedia.org/wiki/YouTube#Quality_and_formats
module.exports = [
  /**
   * 2D Non-DASH
   */
  {
    itag: '17',
    container: '3GP',
    resolution: '144p',
    encoding: 'MPEG-4 Visual',
    profile: 'Simple',
    bitrate: '0.05',
    audioEncoding: 'AAC',
    audioBitrate: 24,
  },
  {
    itag: '36',
    container: '3GP',
    resolution: '240p',
    encoding: 'MPEG-4 Visual',
    profile: 'Simple',
    bitrate: '0.175',
    audioEncoding: 'AAC',
    audioBitrate: 32,
  },
  {
    itag: '5',
    container: 'FLV',
    resolution: '240p',
    encoding: 'Sorenson H.263',
    profile: null,
    bitrate: '0.25',
    audioEncoding: 'MP3',
    audioBitrate: 64,
  },
  {
    itag: '18',
    container: 'MP4',
    resolution: '360p',
    encoding: 'H.264',
    profile: 'Baseline',
    bitrate: '0.5',
    audioEncoding: 'AAC',
    audioBitrate: 96,
  },
  {
    itag: '22',
    container: 'MP4',
    resolution: '720p',
    encoding: 'H.264',
    profile: 'High',
    bitrate: '2-3',
    audioEncoding: 'AAC',
    audioBitrate: 192,
  },
  {
    itag: '43',
    container: 'WebM',
    resolution: '360p',
    encoding: 'VP8',
    profile: null,
    bitrate: '0.5',
    audioEncoding: 'Vorbis',
    audioBitrate: 128,
  },
  /**
   * 3D Non-DASH
   */
  {
    itag: '82',
    container: 'MP4',
    resolution: '360p',
    encoding: 'H.264',
    profile: '3D',
    bitrate: '0.5',
    audioEncoding: 'AAC',
    audioBitrate: 96,
  },
  {
    itag: '83',
    container: 'MP4',
    resolution: '240p',
    encoding: 'H.264',
    profile: '3D',
    bitrate: '0.5',
    audioEncoding: 'AAC',
    audioBitrate: 96,
  },
  {
    itag: '84',
    container: 'MP4',
    resolution: '720p',
    encoding: 'H.264',
    profile: '3D',
    bitrate: '2-3',
    audioEncoding: 'AAC',
    audioBitrate: 192,
  },
  {
    itag: '85',
    container: 'MP4',
    resolution: '1080p',
    encoding: 'H.264',
    profile: '3D',
    bitrate: '3-4',
    audioEncoding: 'AAC',
    audioBitrate: 192,
  },
  {
    itag: '100',
    container: 'WebM',
    resolution: '360p',
    encoding: 'VP8',
    profile: '3D',
    bitrate: null,
    audioEncoding: 'Vorbis',
    audioBitrate: 128,
  },
  /**
   * DASH (video only)
   */
  {
    itag: '160',
    container: 'MP4',
    resolution: '144p',
    encoding: 'H.264',
    profile: 'Main',
    bitrate: '0.1',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '133',
    container: 'MP4',
    resolution: '240p',
    encoding: 'H.264',
    profile: 'Main',
    bitrate: '0.2-0.3',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '134',
    container: 'MP4',
    resolution: '360p',
    encoding: 'H.264',
    profile: 'Main',
    bitrate: '0.3-0.4',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '135',
    container: 'MP4',
    resolution: '480p',
    encoding: 'H.264',
    profile: 'Main',
    bitrate: '0.5-1',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '136',
    container: 'MP4',
    resolution: '720p',
    encoding: 'H.264',
    profile: 'Main',
    bitrate: '1-1.5',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '298',
    container: 'MP4',
    resolution: '720p',
    encoding: 'H.264',
    profile: 'Main',
    bitrate: '3-3.5',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '137',
    container: 'MP4',
    resolution: '1080p',
    encoding: 'H.264',
    profile: 'High',
    bitrate: '2.5-3',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '299',
    container: 'MP4',
    resolution: '1080p',
    encoding: 'H.264',
    profile: 'High',
    bitrate: '5.5',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '264',
    container: 'MP4',
    resolution: '1440p',
    encoding: 'H.264',
    profile: 'High',
    bitrate: '4-4.5',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '266',
    container: 'MP4',
    resolution: '2160p-2304p',
    encoding: 'H.264',
    profile: 'High',
    bitrate: '12.5-16',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '138',
    container: 'MP4',
    resolution: '2160p-4320p',
    encoding: 'H.264',
    profile: 'High',
    bitrate: '13.5-25',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '278',
    container: 'WebM',
    resolution: '144p',
    encoding: 'VP9',
    profile: null,
    bitrate: '0.08',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '242',
    container: 'WebM',
    resolution: '240p',
    encoding: 'VP9',
    profile: null,
    bitrate: '0.1-0.2',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '243',
    container: 'WebM',
    resolution: '360p',
    encoding: 'VP9',
    profile: null,
    bitrate: '0.25',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '244',
    container: 'WebM',
    resolution: '480p',
    encoding: 'VP9',
    profile: null,
    bitrate: '0.5',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '247',
    container: 'WebM',
    resolution: '720p',
    encoding: 'VP9',
    profile: null,
    bitrate: '0.7-0.8',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '248',
    container: 'WebM',
    resolution: '1080p',
    encoding: 'VP9',
    profile: null,
    bitrate: '1.5',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '271',
    container: 'WebM',
    resolution: '1440p',
    encoding: 'VP9',
    profile: null,
    bitrate: '9',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '313',
    container: 'WebM',
    resolution: '2160p',
    encoding: 'VP9',
    profile: null,
    bitrate: '13-15',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '302',
    container: 'WebM',
    resolution: '720p',
    encoding: 'VP9',
    profile: null,
    bitrate: '2.5',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '303',
    container: 'WebM',
    resolution: '1080p',
    encoding: 'VP9',
    profile: null,
    bitrate: '5',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '308',
    container: 'WebM',
    resolution: '1440p',
    encoding: 'VP9',
    profile: null,
    bitrate: '10',
    audioEncoding: null,
    audioBitrate: null,
  },
  {
    itag: '315',
    container: 'WebM',
    resolution: '2160p',
    encoding: 'VP9',
    profile: null,
    bitrate: '20-25',
    audioEncoding: null,
    audioBitrate: null,
  },
  /**
   * DASH (audio only)
   */
  {
    itag: '140',
    container: 'M4A',
    resolution: null,
    encoding: null,
    profile: null,
    bitrate: null,
    audioEncoding: 'AAC',
    audioBitrate: 128,
  },
  {
    itag: '141',
    container: 'M4A',
    resolution: null,
    encoding: null,
    profile: null,
    bitrate: null,
    audioEncoding: 'AAC',
    audioBitrate: 256,
  },
  {
    itag: '171',
    container: 'WebM',
    resolution: null,
    encoding: null,
    profile: null,
    bitrate: null,
    audioEncoding: 'Vorbis',
    audioBitrate: 128,
  },
  {
    itag: '249',
    container: 'WebM',
    resolution: null,
    encoding: null,
    profile: null,
    bitrate: null,
    audioEncoding: 'Opus',
    audioBitrate: 48,
  },
  {
    itag: '250',
    container: 'WebM',
    resolution: null,
    encoding: null,
    profile: null,
    bitrate: null,
    audioEncoding: 'Opus',
    audioBitrate: 64,
  },
  {
    itag: '251',
    container: 'WebM',
    resolution: null,
    encoding: null,
    profile: null,
    bitrate: null,
    audioEncoding: 'Opus',
    audioBitrate: 160,
  },
  /**
   * Live streaming
   */
  {
    itag: '132',
    container: 'TS',
    resolution: '240p',
    encoding: 'H.264',
    profile: 'Baseline',
    bitrate: '0.15-0.2',
    audioEncoding: 'AAC',
    audioBitrate: 48,
  },
  {
    itag: '151',
    container: 'TS',
    resolution: '720p',
    encoding: 'H.264',
    profile: 'Baseline',
    bitrate: '0.05',
    audioEncoding: 'AAC',
    audioBitrate: 24,
  },
  {
    itag: '92',
    container: 'TS',
    resolution: '240p',
    encoding: 'H.264',
    profile: 'Main',
    bitrate: '0.15-0.3',
    audioEncoding: 'AAC',
    audioBitrate: 48,
  },
  {
    itag: '93',
    container: 'TS',
    resolution: '360p',
    encoding: 'H.264',
    profile: 'Main',
    bitrate: '0.5-1',
    audioEncoding: 'AAC',
    audioBitrate: 128,
  },
  {
    itag: '94',
    container: 'TS',
    resolution: '480p',
    encoding: 'H.264',
    profile: 'Main',
    bitrate: '0.8-1.25',
    audioEncoding: 'AAC',
    audioBitrate: 128,
  },
  {
    itag: '95',
    container: 'TS',
    resolution: '720p',
    encoding: 'H.264',
    profile: 'Main',
    bitrate: '1.5-3',
    audioEncoding: 'AAC',
    audioBitrate: 256,
  },
  {
    itag: '96',
    container: 'TS',
    resolution: '1080p',
    encoding: 'H.264',
    profile: 'High',
    bitrate: '2.5-6',
    audioEncoding: 'AAC',
    audioBitrate: 256,
  },
  {
    itag: '127',
    container: 'TS',
    resolution: 'Audio Only',
    encoding: null,
    profile: null,
    bitrate: null,
    audioEncoding: 'AAC',
    audioBitrate: 96,
  },
  {
    itag: '128',
    container: 'TS',
    resolution: 'Audio Only',
    encoding: null,
    profile: null,
    bitrate: null,
    audioEncoding: 'AAC',
    audioBitrate: 96,
  },
];
